<?php

namespace Database\Seeders;

use App\Models\CruiseCompany;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CruiseCompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        CruiseCompany::insert([
            ['name' => 'Azamara Club Cruises', 'description' => '<p>Azamara Club Cruises offers an unparalleled boutique cruise experience with intimate ships, immersive itineraries, and exceptional onboard service. Whether you’re exploring the Mediterranean or the Caribbean, Azamara promises a journey filled with cultural discoveries, gourmet dining, and luxurious accommodations.</p>', 'img' => 'azamara.jpg', 'tp' => '+94771234567'],
            ['name' => 'Carnival Cruise Lines', 'description' => '<p>Join the fun aboard Carnival Cruise Lines and discover why they’re known as the "Fun Ships." With a wide range of activities, entertainment options, and destinations, Carnival offers something for everyone. From vibrant nightlife to relaxing spa treatments, Carnival ensures a memorable vacation at sea.</p>', 'img' => 'carnival.jpg', 'tp' => '+94771234568'],
            ['name' => 'Celebrity Cruises', 'description' => '<p>Celebrity Cruises stands out with its modern luxury approach, featuring stylish ships, innovative dining, and world-class service. Explore destinations around the globe while enjoying top-notch amenities, sophisticated entertainment, and rejuvenating wellness experiences onboard.</p>', 'img' => 'celebrity.jpg', 'tp' => '+94771234569'],
            ['name' => 'Celestyal Cruises', 'description' => '<p>Celestyal Cruises offers authentic, immersive travel experiences in the Eastern Mediterranean. With a focus on Greek hospitality and culture, passengers can explore iconic destinations like the Greek Isles, Cyprus, and Turkey, all while enjoying exceptional onboard service and cuisine.</p>', 'img' => 'celestyal.jpg', 'tp' => '+94771234570'],
            ['name' => 'Costa Cruises', 'description' => '<p>Costa Cruises brings the charm and style of Italy to the high seas. With a fleet of stunning ships, Costa offers diverse itineraries, exceptional dining, and lively entertainment. Whether cruising the Mediterranean or the Caribbean, Costa ensures an unforgettable voyage for all guests.</p>', 'img' => 'costa.jpg', 'tp' => '+94771234571'],
            ['name' => 'Crystal Cruises', 'description' => '<p>Crystal Cruises is renowned for its all-inclusive luxury experience, with elegant ships, award-winning service, and extraordinary itineraries. Guests can enjoy gourmet dining, enriching activities, and unparalleled accommodations while exploring some of the world’s most fascinating destinations.</p>', 'img' => 'crystal.jpg', 'tp' => '+94771234572'],
            ['name' => 'Cunard', 'description' => '<p>Step aboard Cunard’s iconic ocean liners and experience the grandeur of maritime tradition. With a rich history and impeccable service, Cunard offers transatlantic crossings, world cruises, and itineraries to exotic destinations. Indulge in fine dining, elegant entertainment, and luxurious accommodations.</p>', 'img' => 'cunard.jpg', 'tp' => '+94771234573'],
            ['name' => 'Disney Cruise Line', 'description' => '<p>Disney Cruise Line creates magical experiences for families and guests of all ages. With enchanting ships, themed entertainment, and immersive activities, Disney cruises offer the perfect blend of fun and relaxation. Set sail to dream destinations with your favorite Disney characters.</p>', 'img' => 'disney.jpg', 'tp' => '+94771234574'],
            ['name' => 'Holland America Line', 'description' => '<p>Holland America Line combines classic elegance with modern amenities to deliver exceptional cruising experiences. With a diverse range of itineraries, world-class dining, and enriching activities, Holland America offers something for every traveler, from the adventurous to the sophisticated.</p>', 'img' => 'holland.jpg', 'tp' => '+94771234575'],
            ['name' => 'Hurtigruten Expeditions', 'description' => '<p>Embark on an unforgettable adventure with Hurtigruten Expeditions, known for their exploration-focused cruises to remote and pristine destinations. From the polar regions to the Norwegian coast, Hurtigruten offers immersive travel experiences with a focus on sustainability and discovery.</p>', 'img' => 'hurtigruten.jpg', 'tp' => '+94771234576'],
            ['name' => 'MSC Cruises', 'description' => '<p>MSC Cruises brings European flair to the high seas with its modern fleet, stylish design, and exceptional itineraries. Offering a blend of relaxation and entertainment, MSC ensures a memorable experience for guests of all ages. Discover the beauty of the Mediterranean, Caribbean, and beyond with MSC Cruises.</p>', 'img' => 'msc.jpg', 'tp' => '+94771234577'],
            ['name' => 'Norwegian Cruise Line', 'description' => '<p>Norwegian Cruise Line offers a unique Freestyle Cruising concept, allowing guests the freedom to customize their cruise experience. With diverse dining options, exciting entertainment, and flexible itineraries, Norwegian ensures a relaxed and enjoyable vacation for all.</p>', 'img' => 'norwegian.jpg', 'tp' => '+94771234578'],
            ['name' => 'Oceania Cruises', 'description' => '<p>Oceania Cruises is known for its luxurious ships, gourmet dining, and destination-focused itineraries. With a commitment to excellence in every aspect of the cruise experience, Oceania offers guests the chance to explore the world in style and comfort.</p>', 'img' => 'oceania.jpg', 'tp' => '+94771234579'],
            ['name' => 'Princess Cruises', 'description' => '<p>Princess Cruises combines modern amenities with a relaxed atmosphere to deliver an exceptional cruising experience. With a wide range of itineraries, elegant ships, and award-winning service, Princess offers something for every traveler, from the adventurous to the leisurely.</p>', 'img' => 'princess.jpg', 'tp' => '+94771234580'],
            ['name' => 'Regent Seven Seas', 'description' => '<p>Regent Seven Seas offers an all-inclusive luxury cruise experience, with spacious suites, gourmet dining, and personalized service. Guests can explore the world’s most exotic destinations in comfort and style, with everything from shore excursions to gratuities included.</p>', 'img' => 'regent.jpg', 'tp' => '+94771234581'],
            ['name' => 'Royal Caribbean International', 'description' => '<p>Royal Caribbean International offers an unmatched array of activities, entertainment, and dining options on its innovative ships. With itineraries to destinations around the world, Royal Caribbean provides an exciting and memorable vacation experience for guests of all ages.</p>', 'img' => 'royal.jpg', 'tp' => '+94771234582'],
            ['name' => 'Seabourn', 'description' => '<p>Seabourn delivers an ultra-luxury cruise experience with intimate ships, personalized service, and world-class amenities. Guests can explore exotic destinations in style, enjoying gourmet dining, spacious suites, and enriching activities along the way.</p>', 'img' => 'seabourn.jpg', 'tp' => '+94771234583'],
            ['name' => 'Silversea', 'description' => '<p>Silversea offers an ultra-luxury cruise experience with all-inclusive amenities, elegant ships, and exceptional service. Guests can explore remote and exotic destinations in style, with personalized service, gourmet dining, and spacious accommodations.</p>', 'img' => 'silversea.jpg', 'tp' => '+94771234584'],
            ['name' => 'Viking Ocean Cruises', 'description' => '<p>Viking Ocean Cruises offers a unique and immersive travel experience with destination-focused itineraries, elegant ships, and exceptional service. Guests can explore the world’s most fascinating destinations in comfort and style, enjoying gourmet dining, enriching activities, and luxurious accommodations.</p>', 'img' => 'viking.jpg', 'tp' => '+94771234585'],
            ['name' => 'Virgin Voyages', 'description' => '<p>Virgin Voyages brings a fresh and modern approach to cruising, with sleek ships, innovative dining, and vibrant entertainment. Offering adults-only cruises, Virgin Voyages provides a fun and relaxed atmosphere for guests looking to explore the high seas in style.</p>', 'img' => 'virgin.jpg', 'tp' => '+94771234586']
        ]);
    }
}
