<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Full Package',
                's_id' => '1',
                'is_d' => true,
                'is_bl' => false,
                'is_en' => true,
                'is_c' => false,
                'is_ona' => true,
                'is_outa' => false,
                'is_kt' => true,
                'is_w' => false,
                'is_s' => true,
            ],
            [
                'name' => 'Luxury Package',
                's_id' => '2',
                'is_d' => true,
                'is_bl' => true,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => true,
                'is_outa' => true,
                'is_kt' => true,
                'is_w' => true,
                'is_s' => true,
            ],
            [
                'name' => 'Adventure Package',
                's_id' => '3',
                'is_d' => true,
                'is_bl' => false,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => false,
                'is_outa' => true,
                'is_kt' => false,
                'is_w' => false,
                'is_s' => true,
            ],
            [
                'name' => 'Family Package',
                's_id' => '4',
                'is_d' => true,
                'is_bl' => true,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => true,
                'is_outa' => true,
                'is_kt' => true,
                'is_w' => false,
                'is_s' => true,
            ],
            [
                'name' => 'Budget Package',
                's_id' => '5',
                'is_d' => false,
                'is_bl' => true,
                'is_en' => false,
                'is_c' => false,
                'is_ona' => false,
                'is_outa' => true,
                'is_kt' => true,
                'is_w' => true,
                'is_s' => false,
            ],
            [
                'name' => 'Exclusive Package',
                's_id' => '6',
                'is_d' => true,
                'is_bl' => true,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => true,
                'is_outa' => false,
                'is_kt' => true,
                'is_w' => true,
                'is_s' => true,
            ],
            [
                'name' => 'Economy Package',
                's_id' => '7',
                'is_d' => false,
                'is_bl' => true,
                'is_en' => false,
                'is_c' => false,
                'is_ona' => true,
                'is_outa' => true,
                'is_kt' => false,
                'is_w' => false,
                'is_s' => false,
            ],
            [
                'name' => 'Premium Package',
                's_id' => '8',
                'is_d' => true,
                'is_bl' => true,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => true,
                'is_outa' => false,
                'is_kt' => true,
                'is_w' => true,
                'is_s' => true,
            ],
            [
                'name' => 'Standard Package',
                's_id' => '9',
                'is_d' => false,
                'is_bl' => true,
                'is_en' => false,
                'is_c' => true,
                'is_ona' => false,
                'is_outa' => true,
                'is_kt' => false,
                'is_w' => true,
                'is_s' => false,
            ],
            [
                'name' => 'Luxury Package 2',
                's_id' => '10',
                'is_d' => true,
                'is_bl' => true,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => true,
                'is_outa' => true,
                'is_kt' => true,
                'is_w' => true,
                'is_s' => true,
            ],
            [
                'name' => 'Full Package 2',
                's_id' => '11',
                'is_d' => false,
                'is_bl' => true,
                'is_en' => false,
                'is_c' => true,
                'is_ona' => false,
                'is_outa' => true,
                'is_kt' => false,
                'is_w' => true,
                'is_s' => false,
            ],
            [
                'name' => 'Adventure Package 2',
                's_id' => '12',
                'is_d' => true,
                'is_bl' => false,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => false,
                'is_outa' => true,
                'is_kt' => false,
                'is_w' => false,
                'is_s' => true,
            ],
            [
                'name' => 'Family Package 2',
                's_id' => '13',
                'is_d' => true,
                'is_bl' => true,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => true,
                'is_outa' => true,
                'is_kt' => true,
                'is_w' => false,
                'is_s' => true,
            ],
            [
                'name' => 'Budget Package 2',
                's_id' => '14',
                'is_d' => false,
                'is_bl' => true,
                'is_en' => false,
                'is_c' => false,
                'is_ona' => false,
                'is_outa' => true,
                'is_kt' => true,
                'is_w' => true,
                'is_s' => false,
            ],
            [
                'name' => 'Exclusive Package 2',
                's_id' => '15',
                'is_d' => true,
                'is_bl' => true,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => true,
                'is_outa' => false,
                'is_kt' => true,
                'is_w' => true,
                'is_s' => true,
            ],
            [
                'name' => 'Economy Package 2',
                's_id' => '16',
                'is_d' => false,
                'is_bl' => true,
                'is_en' => false,
                'is_c' => false,
                'is_ona' => true,
                'is_outa' => true,
                'is_kt' => false,
                'is_w' => false,
                'is_s' => false,
            ],
            [
                'name' => 'Premium Package 2',
                's_id' => '17',
                'is_d' => true,
                'is_bl' => true,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => true,
                'is_outa' => false,
                'is_kt' => true,
                'is_w' => true,
                'is_s' => true,
            ],
            [
                'name' => 'Standard Package 2',
                's_id' => '18',
                'is_d' => false,
                'is_bl' => true,
                'is_en' => false,
                'is_c' => true,
                'is_ona' => false,
                'is_outa' => true,
                'is_kt' => false,
                'is_w' => true,
                'is_s' => false,
            ],
            [
                'name' => 'Luxury Package 3',
                's_id' => '19',
                'is_d' => true,
                'is_bl' => true,
                'is_en' => true,
                'is_c' => true,
                'is_ona' => true,
                'is_outa' => true,
                'is_kt' => true,
                'is_w' => true,
                'is_s' => true,
            ],
            [
                'name' => 'Full Package 3',
                's_id' => '20',
                'is_d' => false,
                'is_bl' => true,
                'is_en' => false,
                'is_c' => true,
                'is_ona' => false,
                'is_outa' => true,
                'is_kt' => false,
                'is_w' => true,
                'is_s' => false,
            ],
        ];

        Package::insert($data);
    }
}
